<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CVRanker.Contracts\CVRanker.Contracts.csproj" />
    <ProjectReference Include="..\CVRanker.Application\CVRanker.Application.csproj" />
    <ProjectReference Include="..\CVRanker.Infrastructure\CVRanker.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
